---
title: "Analysis Workflow for whole dataset"
author: "João Vitor"
date: "06/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading-packages}
library(tidyverse)
library(tidytext)
library(spacyr)
library(igraph)
library(ggraph)

set.seed(112358)

theme_set(theme_bw(base_family = "Roboto"))

spacy_initialize(model = "en_ner_craft_md", condaenv = "~/miniconda3/envs/spacy-proc")
```

```{r loading-data}

litcovid <- jsonlite::fromJSON("./data/raw/litcovid2BioCJSON")[[2]] %>% 
  as_tibble() %>% 
  sample_n(9000)

```

```{r text-wrangling}
texts <- c()

for (t in litcovid$passages) {
  catted <- str_to_lower(paste(t[[3]], collapse = ' '))
  texts <- append(texts, catted)
}

litcovid <- litcovid %>% 
  select(-c(`_id`, authors, infons)) %>% 
  mutate(text = texts) %>%
  unnest(cols = c(tags, accessions))
```

## Text relationships

```{r bigrams}
litcovid_bigrams <- litcovid %>% 
  unnest_tokens(bigram, text, token = "ngrams", n = 2, collapse = FALSE) %>%
  separate(bigram, c("word1", "word2"), sep = " ") %>% 
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word) %>% 
  select(-c(id, passages, pmcid, created, year, tags, accessions)) %>% 
  count(word1, word2, sort = TRUE)

bigram_graph <- litcovid_bigrams %>% 
  filter(n > 25) %>%
  graph_from_data_frame() 

a <- grid::arrow(type = "closed", length = unit(.15, "inches"))

bigram_graph %>% 
  ggraph(layout = "fr") +
    geom_edge_link(aes(edge_alpha = n), show.legend = FALSE, arrow = a) +
    geom_node_point(color = "#D8BFD8", size = 3) +
    geom_node_text(aes(label = name), check_overlap = TRUE, vjust = 1, hjust = 1) +
    theme_void()
```

## Named entity recognition workflow

```{r entity-extraction}
parsed_passages <- spacy_parse(litcovid$text, pos = FALSE) 

parsed_only_entity <- parsed_passages %>% 
  filter(entity != "")

entity_table <- parsed_passages %>% 
  entity_extract(concatenator = " ") %>% 
  # The following steps are to ensure we get the lemmatized version of the entity,
  # This avoids getting slightly different entities that mean the same thing
  left_join(parsed_only_entity[c("doc_id","sentence_id", "token", "lemma")], 
            by = c("doc_id","sentence_id", "entity" = "token")) %>% 
  mutate(term = ifelse(is.na(lemma), entity, lemma),
         entity_type_name = case_when(
           entity_type == "CHEBI" ~ "ChEBI Entity",
           entity_type == "GGP" ~ "Gene or Gene Product",
           entity_type == "CL" ~ "Cell Ontology Term",
           entity_type == "SO" ~ "Sequence Ontology Term",
           entity_type == "GO" ~ "Gene Ontology Entity",
           entity_type == "TAXON" ~ "NCBITaxonomy Entity"
         )) %>% 
  # Maybe this entity means positive strand? I'm not so sure so I'm filtering it out
  filter(term != "+")

entity_counts <- entity_table %>%  
  count(entity_type_name, term, sort = TRUE) 

top_15_entities <- entity_counts %>% 
  group_by(entity_type_name) %>% 
  top_n(15) %>% 
  ungroup() %>% 
  # Taxon is better suited on it's own plot to avoid a huge change in the scale
  filter(entity_type_name != "NCBITaxonomy Entity")
  mutate(text = reorder_within(term, n, entity_type_name))

top_by_tfidf <- entity_counts %>% 
  bind_tf_idf(term = term, document = entity_type_name, n = n) %>% 
  group_by(entity_type_name) %>% 
  top_n(15, tf_idf) %>% 
  ungroup() %>% 
  mutate(text = reorder_within(term, n, entity_type_name))
```


```{r entity-plotting}
ggplot(top_15_entities, aes(y = text, x = n, fill = entity_type_name)) + 
  geom_col() + 
  guides(fill = FALSE) +
  labs(x = "Count", y = NULL, 
       title = "15 most frequent entities",
       subtitle = "Grouped by entity type") +
  facet_wrap(~ entity_type_name, scales = "free_y") +
  scale_y_reordered() +
  scale_fill_viridis_d(option = 'magma', end = 0.8) +
  theme(plot.title = element_text(face = "bold"))

ggplot(top_by_tfidf, aes(y = text, x = tf_idf, fill = entity_type_name)) + 
  geom_col() + 
  guides(fill = FALSE) +
  labs(x = "Tf-Idf", y = NULL, 
       title = "15 most frequent entities",
       subtitle = "Grouped by entity type") +
  facet_wrap(~ entity_type_name, scales = "free_y") +
  scale_y_reordered() +
  scale_fill_viridis_d(option = 'magma', end = 0.8) +
  theme(plot.title = element_text(face = "bold"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) 
```

```{r}
save(litcovid_bigrams, entity_counts, file = "./data/processed/objects_for_plotting.rda")
```

