---
title: "Initial analysis"
author: "João Vitor"
date: "06/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Named entity recognition workflow

```{r loading-packages}
library(tidyverse)
library(tidytext)
library(spacyr)
theme_set(theme_bw(base_family = "Roboto"))

spacy_initialize(model = "en_ner_craft_md", condaenv = "~/miniconda3/envs/spacy-proc")
```

```{r loading-data}

pubtator_annot <- jsonlite::fromJSON("./litcovid2BioCJSON")[[2]] %>% 
  as_tibble() %>% 
  sample_n(9000)

```

```{r text-wrangling}
texts <- c()

for (t in pubtator_annot$passages) {
  catted <- str_to_lower(paste(t[[3]], collapse = ' '))
  texts <- append(texts, catted)
}

pubtator_annot <- pubtator_annot %>% 
  select(-c(`_id`, authors, infons)) %>% 
  mutate(text = texts) %>%
  unnest(cols = c(tags, accessions))
```

```{r entity-extraction}
parsed_passages <- spacy_parse(pubtator_annot$text, pos = FALSE) 

parsed_only_entity <- parsed_passages %>% 
  filter(entity != "")

entity_table <- parsed_passages %>% 
  entity_extract(concatenator = " ") %>% 
  # The following steps are to ensure we get the lemmatized version of the entity,
  # This avoids getting slightly different entities that mean the same thing
  left_join(parsed_only_entity[c("doc_id","sentence_id", "token", "lemma")], 
            by = c("doc_id","sentence_id", "entity" = "token")) %>% 
  mutate(term = ifelse(is.na(lemma), entity, lemma),
         entity_name = case_when(
           entity_type == "CHEBI" ~ "ChEBI Entity",
           entity_type == "GGP" ~ "Gene or Gene Product",
           entity_type == "CL" ~ "Cell Ontology Term",
           entity_type == "SO" ~ "Sequence Ontology Term",
           entity_type == "GO" ~ "Gene Ontology Entity",
           entity_type == "TAXON" ~ "NCBITaxonomy Entity"
         )) %>% 
  # Maybe this entity means positive strand? I'm not so sure so I'm filtering it out
  filter(term != "+")

top_15_entities <- entity_table %>%  
  count(entity_name, term, sort = TRUE) %>% 
  group_by(entity_name) %>% 
  top_n(15) %>% 
  ungroup() %>% 
  # Taxon is better suited on it's own plot to avoid a huge change in the scale
  filter(entity_name != "NCBITaxonomy Entity") %>% 
  mutate(text = reorder_within(term, n, entity_name))
```


```{r entity-plotting}
ggplot(top_15_entities, aes(y = text, x = n, fill = entity_name)) + 
  geom_col() + 
  guides(fill = FALSE) +
  labs(y = "Count", x = NULL, 
       title = "15 most frequent entities",
       subtitle = "Grouped by entity type") +
  facet_wrap(~ entity_name, scales = "free_y") +
  scale_y_reordered() +
  scale_fill_viridis_d(option = 'magma', end = 0.8) +
  theme(plot.title = element_text(face = "bold"))
```

